//VJOB0412 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//RUNPROC  PROC MEM=DEFAULT
//*
//STEP01   EXEC PGM=ZRE09931
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDREIN67 DD DISP=SHR,DSN=GENAPP.DDREIN67.DATA
//DDREOT67 DD DISP=SHR,DSN=GENAPP.DDREOT67.DATA
//DDRERP67 DD DISP=SHR,DSN=GENAPP.DDRERP67.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG09932
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDAGIN68 DD DISP=SHR,DSN=GENAPP.DDAGIN68.DATA
//DDAGOT68 DD DISP=SHR,DSN=GENAPP.DDAGOT68.DATA
//DDAGRP68 DD DISP=SHR,DSN=GENAPP.DDAGRP68.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA09933
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDPAIN69 DD DISP=SHR,DSN=GENAPP.DDPAIN69.DATA
//DDPAOT69 DD DISP=SHR,DSN=GENAPP.DDPAOT69.DATA
//DDPARP69 DD DISP=SHR,DSN=GENAPP.DDPARP69.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//         PEND
//RUN      EXEC RUNPROC,MEM=VOLTEST
//
