//VJOB0265 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//RUNPROC  PROC MEM=DEFAULT
//*
//STEP01   EXEC PGM=ZEN09490
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDENIN76 DD DISP=SHR,DSN=GENAPP.DDENIN76.DATA
//DDENOT76 DD DISP=SHR,DSN=GENAPP.DDENOT76.DATA
//DDENRP76 DD DISP=SHR,DSN=GENAPP.DDENRP76.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI09491
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDBIIN77 DD DISP=SHR,DSN=GENAPP.DDBIIN77.DATA
//DDBIOT77 DD DISP=SHR,DSN=GENAPP.DDBIOT77.DATA
//DDBIRP77 DD DISP=SHR,DSN=GENAPP.DDBIRP77.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW09492
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDUWIN78 DD DISP=SHR,DSN=GENAPP.DDUWIN78.DATA
//DDUWOT78 DD DISP=SHR,DSN=GENAPP.DDUWOT78.DATA
//DDUWRP78 DD DISP=SHR,DSN=GENAPP.DDUWRP78.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//         PEND
//RUN      EXEC RUNPROC,MEM=VOLTEST
//
