//VJOB0391 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU09868
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN04 DD DISP=SHR,DSN=GENAPP.DDCUIN04.DATA
//DDCUOT04 DD DISP=SHR,DSN=GENAPP.DDCUOT04.DATA
//DDCURP04 DD DISP=SHR,DSN=GENAPP.DDCURP04.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL09869
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN05 DD DISP=SHR,DSN=GENAPP.DDCLIN05.DATA
//DDCLOT05 DD DISP=SHR,DSN=GENAPP.DDCLOT05.DATA
//DDCLRP05 DD DISP=SHR,DSN=GENAPP.DDCLRP05.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI09870
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN06 DD DISP=SHR,DSN=GENAPP.DDBIIN06.DATA
//DDBIOT06 DD DISP=SHR,DSN=GENAPP.DDBIOT06.DATA
//DDBIRP06 DD DISP=SHR,DSN=GENAPP.DDBIRP06.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
