//VJOB0020 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//RUNPROC  PROC MEM=DEFAULT
//*
//STEP01   EXEC PGM=ZMT08755
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDMTIN61 DD DISP=SHR,DSN=GENAPP.DDMTIN61.DATA
//DDMTOT61 DD DISP=SHR,DSN=GENAPP.DDMTOT61.DATA
//DDMTRP61 DD DISP=SHR,DSN=GENAPP.DDMTRP61.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO08756
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDHOIN62 DD DISP=SHR,DSN=GENAPP.DDHOIN62.DATA
//DDHOOT62 DD DISP=SHR,DSN=GENAPP.DDHOOT62.DATA
//DDHORP62 DD DISP=SHR,DSN=GENAPP.DDHORP62.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN08757
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDENIN63 DD DISP=SHR,DSN=GENAPP.DDENIN63.DATA
//DDENOT63 DD DISP=SHR,DSN=GENAPP.DDENOT63.DATA
//DDENRP63 DD DISP=SHR,DSN=GENAPP.DDENRP63.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//         PEND
//RUN      EXEC RUNPROC,MEM=VOLTEST
//
