//VJOB0369 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG09802
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN28 DD DISP=SHR,DSN=GENAPP.DDAGIN28.DATA
//DDAGOT28 DD DISP=SHR,DSN=GENAPP.DDAGOT28.DATA
//DDAGRP28 DD DISP=SHR,DSN=GENAPP.DDAGRP28.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA09803
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN29 DD DISP=SHR,DSN=GENAPP.DDPAIN29.DATA
//DDPAOT29 DD DISP=SHR,DSN=GENAPP.DDPAOT29.DATA
//DDPARP29 DD DISP=SHR,DSN=GENAPP.DDPARP29.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW09804
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN30 DD DISP=SHR,DSN=GENAPP.DDUWIN30.DATA
//DDUWOT30 DD DISP=SHR,DSN=GENAPP.DDUWOT30.DATA
//DDUWRP30 DD DISP=SHR,DSN=GENAPP.DDUWRP30.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
