//VJOB0072 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE08911
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN37 DD DISP=SHR,DSN=GENAPP.DDREIN37.DATA
//DDREOT37 DD DISP=SHR,DSN=GENAPP.DDREOT37.DATA
//DDRERP37 DD DISP=SHR,DSN=GENAPP.DDRERP37.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG08912
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN38 DD DISP=SHR,DSN=GENAPP.DDAGIN38.DATA
//DDAGOT38 DD DISP=SHR,DSN=GENAPP.DDAGOT38.DATA
//DDAGRP38 DD DISP=SHR,DSN=GENAPP.DDAGRP38.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA08913
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN39 DD DISP=SHR,DSN=GENAPP.DDPAIN39.DATA
//DDPAOT39 DD DISP=SHR,DSN=GENAPP.DDPAOT39.DATA
//DDPARP39 DD DISP=SHR,DSN=GENAPP.DDPARP39.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
