//VJOB0293 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW09574
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN70 DD DISP=SHR,DSN=GENAPP.DDUWIN70.DATA
//DDUWOT70 DD DISP=SHR,DSN=GENAPP.DDUWOT70.DATA
//DDUWRP70 DD DISP=SHR,DSN=GENAPP.DDUWRP70.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT09575
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN71 DD DISP=SHR,DSN=GENAPP.DDMTIN71.DATA
//DDMTOT71 DD DISP=SHR,DSN=GENAPP.DDMTOT71.DATA
//DDMTRP71 DD DISP=SHR,DSN=GENAPP.DDMTRP71.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO09576
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN72 DD DISP=SHR,DSN=GENAPP.DDHOIN72.DATA
//DDHOOT72 DD DISP=SHR,DSN=GENAPP.DDHOOT72.DATA
//DDHORP72 DD DISP=SHR,DSN=GENAPP.DDHORP72.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
