//VJOB0133 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW09094
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN40 DD DISP=SHR,DSN=GENAPP.DDUWIN40.DATA
//DDUWOT40 DD DISP=SHR,DSN=GENAPP.DDUWOT40.DATA
//DDUWRP40 DD DISP=SHR,DSN=GENAPP.DDUWRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT09095
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN41 DD DISP=SHR,DSN=GENAPP.DDMTIN41.DATA
//DDMTOT41 DD DISP=SHR,DSN=GENAPP.DDMTOT41.DATA
//DDMTRP41 DD DISP=SHR,DSN=GENAPP.DDMTRP41.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO09096
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN42 DD DISP=SHR,DSN=GENAPP.DDHOIN42.DATA
//DDHOOT42 DD DISP=SHR,DSN=GENAPP.DDHOOT42.DATA
//DDHORP42 DD DISP=SHR,DSN=GENAPP.DDHORP42.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
