//VJOB0124 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN09067
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN13 DD DISP=SHR,DSN=GENAPP.DDENIN13.DATA
//DDENOT13 DD DISP=SHR,DSN=GENAPP.DDENOT13.DATA
//DDENRP13 DD DISP=SHR,DSN=GENAPP.DDENRP13.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU09068
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN14 DD DISP=SHR,DSN=GENAPP.DDCUIN14.DATA
//DDCUOT14 DD DISP=SHR,DSN=GENAPP.DDCUOT14.DATA
//DDCURP14 DD DISP=SHR,DSN=GENAPP.DDCURP14.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL09069
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN15 DD DISP=SHR,DSN=GENAPP.DDCLIN15.DATA
//DDCLOT15 DD DISP=SHR,DSN=GENAPP.DDCLOT15.DATA
//DDCLRP15 DD DISP=SHR,DSN=GENAPP.DDCLRP15.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
