//VJOB0392 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE09871
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN07 DD DISP=SHR,DSN=GENAPP.DDREIN07.DATA
//DDREOT07 DD DISP=SHR,DSN=GENAPP.DDREOT07.DATA
//DDRERP07 DD DISP=SHR,DSN=GENAPP.DDRERP07.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG09872
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN08 DD DISP=SHR,DSN=GENAPP.DDAGIN08.DATA
//DDAGOT08 DD DISP=SHR,DSN=GENAPP.DDAGOT08.DATA
//DDAGRP08 DD DISP=SHR,DSN=GENAPP.DDAGRP08.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA09873
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN09 DD DISP=SHR,DSN=GENAPP.DDPAIN09.DATA
//DDPAOT09 DD DISP=SHR,DSN=GENAPP.DDPAOT09.DATA
//DDPARP09 DD DISP=SHR,DSN=GENAPP.DDPARP09.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
