//VJOB0144 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN09127
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN73 DD DISP=SHR,DSN=GENAPP.DDENIN73.DATA
//DDENOT73 DD DISP=SHR,DSN=GENAPP.DDENOT73.DATA
//DDENRP73 DD DISP=SHR,DSN=GENAPP.DDENRP73.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU09128
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN74 DD DISP=SHR,DSN=GENAPP.DDCUIN74.DATA
//DDCUOT74 DD DISP=SHR,DSN=GENAPP.DDCUOT74.DATA
//DDCURP74 DD DISP=SHR,DSN=GENAPP.DDCURP74.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL09129
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN75 DD DISP=SHR,DSN=GENAPP.DDCLIN75.DATA
//DDCLOT75 DD DISP=SHR,DSN=GENAPP.DDCLOT75.DATA
//DDCLRP75 DD DISP=SHR,DSN=GENAPP.DDCLRP75.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
