//VJOB0229 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG09382
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN58 DD DISP=SHR,DSN=GENAPP.DDAGIN58.DATA
//DDAGOT58 DD DISP=SHR,DSN=GENAPP.DDAGOT58.DATA
//DDAGRP58 DD DISP=SHR,DSN=GENAPP.DDAGRP58.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA09383
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN59 DD DISP=SHR,DSN=GENAPP.DDPAIN59.DATA
//DDPAOT59 DD DISP=SHR,DSN=GENAPP.DDPAOT59.DATA
//DDPARP59 DD DISP=SHR,DSN=GENAPP.DDPARP59.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW09384
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN60 DD DISP=SHR,DSN=GENAPP.DDUWIN60.DATA
//DDUWOT60 DD DISP=SHR,DSN=GENAPP.DDUWOT60.DATA
//DDUWRP60 DD DISP=SHR,DSN=GENAPP.DDUWRP60.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
