//VJOB0250 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZMT09445
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN31 DD DISP=SHR,DSN=GENAPP.DDMTIN31.DATA
//DDMTOT31 DD DISP=SHR,DSN=GENAPP.DDMTOT31.DATA
//DDMTRP31 DD DISP=SHR,DSN=GENAPP.DDMTRP31.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZHO09446
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN32 DD DISP=SHR,DSN=GENAPP.DDHOIN32.DATA
//DDHOOT32 DD DISP=SHR,DSN=GENAPP.DDHOOT32.DATA
//DDHORP32 DD DISP=SHR,DSN=GENAPP.DDHORP32.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN09447
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN33 DD DISP=SHR,DSN=GENAPP.DDENIN33.DATA
//DDENOT33 DD DISP=SHR,DSN=GENAPP.DDENOT33.DATA
//DDENRP33 DD DISP=SHR,DSN=GENAPP.DDENRP33.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
