//VJOB0351 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU09748
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN64 DD DISP=SHR,DSN=GENAPP.DDCUIN64.DATA
//DDCUOT64 DD DISP=SHR,DSN=GENAPP.DDCUOT64.DATA
//DDCURP64 DD DISP=SHR,DSN=GENAPP.DDCURP64.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL09749
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN65 DD DISP=SHR,DSN=GENAPP.DDCLIN65.DATA
//DDCLOT65 DD DISP=SHR,DSN=GENAPP.DDCLOT65.DATA
//DDCLRP65 DD DISP=SHR,DSN=GENAPP.DDCLRP65.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI09750
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN66 DD DISP=SHR,DSN=GENAPP.DDBIIN66.DATA
//DDBIOT66 DD DISP=SHR,DSN=GENAPP.DDBIOT66.DATA
//DDBIRP66 DD DISP=SHR,DSN=GENAPP.DDBIRP66.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
