//VJOB0359 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//RUNPROC  PROC MEM=DEFAULT
//*
//STEP01   EXEC PGM=ZEN09772
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDENIN88 DD DISP=SHR,DSN=GENAPP.DDENIN88.DATA
//DDENOT88 DD DISP=SHR,DSN=GENAPP.DDENOT88.DATA
//DDENRP88 DD DISP=SHR,DSN=GENAPP.DDENRP88.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU09773
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDCUIN89 DD DISP=SHR,DSN=GENAPP.DDCUIN89.DATA
//DDCUOT89 DD DISP=SHR,DSN=GENAPP.DDCUOT89.DATA
//DDCURP89 DD DISP=SHR,DSN=GENAPP.DDCURP89.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZEN09774
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//SYSIN    DD DISP=SHR,DSN=GENAPP.PARMLIB(&MEM)
//DDENIN90 DD DISP=SHR,DSN=GENAPP.DDENIN90.DATA
//DDENOT90 DD DISP=SHR,DSN=GENAPP.DDENOT90.DATA
//DDENRP90 DD DISP=SHR,DSN=GENAPP.DDENRP90.DATA
//WORKDS   DD DSN=&&WORK,DISP=(NEW,PASS),UNIT=SYSDA,
//            SPACE=(TRK,(20,10))
//SORTWK   DD DSN=&&SORTWK,DISP=(NEW,DELETE),UNIT=SYSDA,
//            SPACE=(CYL,(5,5))
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//         PEND
//RUN      EXEC RUNPROC,MEM=VOLTEST
//
