//VJOB0239 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZAG09412
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN88 DD DISP=SHR,DSN=GENAPP.DDAGIN88.DATA
//DDAGOT88 DD DISP=SHR,DSN=GENAPP.DDAGOT88.DATA
//DDAGRP88 DD DISP=SHR,DSN=GENAPP.DDAGRP88.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZPA09413
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN89 DD DISP=SHR,DSN=GENAPP.DDPAIN89.DATA
//DDPAOT89 DD DISP=SHR,DSN=GENAPP.DDPAOT89.DATA
//DDPARP89 DD DISP=SHR,DSN=GENAPP.DDPARP89.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZUW09414
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN90 DD DISP=SHR,DSN=GENAPP.DDUWIN90.DATA
//DDUWOT90 DD DISP=SHR,DSN=GENAPP.DDUWOT90.DATA
//DDUWRP90 DD DISP=SHR,DSN=GENAPP.DDUWRP90.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
