//VJOB0396 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA09883
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN19 DD DISP=SHR,DSN=GENAPP.DDPAIN19.DATA
//DDPAOT19 DD DISP=SHR,DSN=GENAPP.DDPAOT19.DATA
//DDPARP19 DD DISP=SHR,DSN=GENAPP.DDPARP19.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW09884
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN20 DD DISP=SHR,DSN=GENAPP.DDUWIN20.DATA
//DDUWOT20 DD DISP=SHR,DSN=GENAPP.DDUWOT20.DATA
//DDUWRP20 DD DISP=SHR,DSN=GENAPP.DDUWRP20.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT09885
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN21 DD DISP=SHR,DSN=GENAPP.DDMTIN21.DATA
//DDMTOT21 DD DISP=SHR,DSN=GENAPP.DDMTOT21.DATA
//DDMTRP21 DD DISP=SHR,DSN=GENAPP.DDMTRP21.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
