//VJOB0378 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL09829
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN55 DD DISP=SHR,DSN=GENAPP.DDCLIN55.DATA
//DDCLOT55 DD DISP=SHR,DSN=GENAPP.DDCLOT55.DATA
//DDCLRP55 DD DISP=SHR,DSN=GENAPP.DDCLRP55.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI09830
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN56 DD DISP=SHR,DSN=GENAPP.DDBIIN56.DATA
//DDBIOT56 DD DISP=SHR,DSN=GENAPP.DDBIOT56.DATA
//DDBIRP56 DD DISP=SHR,DSN=GENAPP.DDBIRP56.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE09831
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN57 DD DISP=SHR,DSN=GENAPP.DDREIN57.DATA
//DDREOT57 DD DISP=SHR,DSN=GENAPP.DDREOT57.DATA
//DDRERP57 DD DISP=SHR,DSN=GENAPP.DDRERP57.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
