//VJOB0177 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO09226
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN82 DD DISP=SHR,DSN=GENAPP.DDHOIN82.DATA
//DDHOOT82 DD DISP=SHR,DSN=GENAPP.DDHOOT82.DATA
//DDHORP82 DD DISP=SHR,DSN=GENAPP.DDHORP82.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN09227
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN83 DD DISP=SHR,DSN=GENAPP.DDENIN83.DATA
//DDENOT83 DD DISP=SHR,DSN=GENAPP.DDENOT83.DATA
//DDENRP83 DD DISP=SHR,DSN=GENAPP.DDENRP83.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU09228
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN84 DD DISP=SHR,DSN=GENAPP.DDCUIN84.DATA
//DDCUOT84 DD DISP=SHR,DSN=GENAPP.DDCUOT84.DATA
//DDCURP84 DD DISP=SHR,DSN=GENAPP.DDCURP84.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
