//VJOB0158 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL09169
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN25 DD DISP=SHR,DSN=GENAPP.DDCLIN25.DATA
//DDCLOT25 DD DISP=SHR,DSN=GENAPP.DDCLOT25.DATA
//DDCLRP25 DD DISP=SHR,DSN=GENAPP.DDCLRP25.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI09170
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN26 DD DISP=SHR,DSN=GENAPP.DDBIIN26.DATA
//DDBIOT26 DD DISP=SHR,DSN=GENAPP.DDBIOT26.DATA
//DDBIRP26 DD DISP=SHR,DSN=GENAPP.DDBIRP26.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE09171
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN27 DD DISP=SHR,DSN=GENAPP.DDREIN27.DATA
//DDREOT27 DD DISP=SHR,DSN=GENAPP.DDREOT27.DATA
//DDRERP27 DD DISP=SHR,DSN=GENAPP.DDRERP27.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
