//VJOB0415 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI09940
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN76 DD DISP=SHR,DSN=GENAPP.DDBIIN76.DATA
//DDBIOT76 DD DISP=SHR,DSN=GENAPP.DDBIOT76.DATA
//DDBIRP76 DD DISP=SHR,DSN=GENAPP.DDBIRP76.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE09941
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN77 DD DISP=SHR,DSN=GENAPP.DDREIN77.DATA
//DDREOT77 DD DISP=SHR,DSN=GENAPP.DDREOT77.DATA
//DDRERP77 DD DISP=SHR,DSN=GENAPP.DDRERP77.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG09942
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN78 DD DISP=SHR,DSN=GENAPP.DDAGIN78.DATA
//DDAGOT78 DD DISP=SHR,DSN=GENAPP.DDAGOT78.DATA
//DDAGRP78 DD DISP=SHR,DSN=GENAPP.DDAGRP78.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
