//VJOB0045 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI08830
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN46 DD DISP=SHR,DSN=GENAPP.DDBIIN46.DATA
//DDBIOT46 DD DISP=SHR,DSN=GENAPP.DDBIOT46.DATA
//DDBIRP46 DD DISP=SHR,DSN=GENAPP.DDBIRP46.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE08831
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN47 DD DISP=SHR,DSN=GENAPP.DDREIN47.DATA
//DDREOT47 DD DISP=SHR,DSN=GENAPP.DDREOT47.DATA
//DDRERP47 DD DISP=SHR,DSN=GENAPP.DDRERP47.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG08832
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN48 DD DISP=SHR,DSN=GENAPP.DDAGIN48.DATA
//DDAGOT48 DD DISP=SHR,DSN=GENAPP.DDAGOT48.DATA
//DDAGRP48 DD DISP=SHR,DSN=GENAPP.DDAGRP48.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
