//VJOB0077 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO08926
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN52 DD DISP=SHR,DSN=GENAPP.DDHOIN52.DATA
//DDHOOT52 DD DISP=SHR,DSN=GENAPP.DDHOOT52.DATA
//DDHORP52 DD DISP=SHR,DSN=GENAPP.DDHORP52.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN08927
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN53 DD DISP=SHR,DSN=GENAPP.DDENIN53.DATA
//DDENOT53 DD DISP=SHR,DSN=GENAPP.DDENOT53.DATA
//DDENRP53 DD DISP=SHR,DSN=GENAPP.DDENRP53.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU08928
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN54 DD DISP=SHR,DSN=GENAPP.DDCUIN54.DATA
//DDCUOT54 DD DISP=SHR,DSN=GENAPP.DDCUOT54.DATA
//DDCURP54 DD DISP=SHR,DSN=GENAPP.DDCURP54.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
