//VJOB0416 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZPA09943
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN79 DD DISP=SHR,DSN=GENAPP.DDPAIN79.DATA
//DDPAOT79 DD DISP=SHR,DSN=GENAPP.DDPAOT79.DATA
//DDPARP79 DD DISP=SHR,DSN=GENAPP.DDPARP79.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZUW09944
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN80 DD DISP=SHR,DSN=GENAPP.DDUWIN80.DATA
//DDUWOT80 DD DISP=SHR,DSN=GENAPP.DDUWOT80.DATA
//DDUWRP80 DD DISP=SHR,DSN=GENAPP.DDUWRP80.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZMT09945
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN81 DD DISP=SHR,DSN=GENAPP.DDMTIN81.DATA
//DDMTOT81 DD DISP=SHR,DSN=GENAPP.DDMTOT81.DATA
//DDMTRP81 DD DISP=SHR,DSN=GENAPP.DDMTRP81.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
