//VJOB0433 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW09994
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN40 DD DISP=SHR,DSN=GENAPP.DDUWIN40.DATA
//DDUWOT40 DD DISP=SHR,DSN=GENAPP.DDUWOT40.DATA
//DDUWRP40 DD DISP=SHR,DSN=GENAPP.DDUWRP40.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
