//VJOB0041 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCU08818
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN34 DD DISP=SHR,DSN=GENAPP.DDCUIN34.DATA
//DDCUOT34 DD DISP=SHR,DSN=GENAPP.DDCUOT34.DATA
//DDCURP34 DD DISP=SHR,DSN=GENAPP.DDCURP34.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCL08819
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN35 DD DISP=SHR,DSN=GENAPP.DDCLIN35.DATA
//DDCLOT35 DD DISP=SHR,DSN=GENAPP.DDCLOT35.DATA
//DDCLRP35 DD DISP=SHR,DSN=GENAPP.DDCLRP35.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZBI08820
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN36 DD DISP=SHR,DSN=GENAPP.DDBIIN36.DATA
//DDBIOT36 DD DISP=SHR,DSN=GENAPP.DDBIOT36.DATA
//DDBIRP36 DD DISP=SHR,DSN=GENAPP.DDBIRP36.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
