//VJOB0365 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZBI09790
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN16 DD DISP=SHR,DSN=GENAPP.DDBIIN16.DATA
//DDBIOT16 DD DISP=SHR,DSN=GENAPP.DDBIOT16.DATA
//DDBIRP16 DD DISP=SHR,DSN=GENAPP.DDBIRP16.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZRE09791
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN17 DD DISP=SHR,DSN=GENAPP.DDREIN17.DATA
//DDREOT17 DD DISP=SHR,DSN=GENAPP.DDREOT17.DATA
//DDRERP17 DD DISP=SHR,DSN=GENAPP.DDRERP17.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZAG09792
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN18 DD DISP=SHR,DSN=GENAPP.DDAGIN18.DATA
//DDAGOT18 DD DISP=SHR,DSN=GENAPP.DDAGOT18.DATA
//DDAGRP18 DD DISP=SHR,DSN=GENAPP.DDAGRP18.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
