//VJOB0148 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZCL09139
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN85 DD DISP=SHR,DSN=GENAPP.DDCLIN85.DATA
//DDCLOT85 DD DISP=SHR,DSN=GENAPP.DDCLOT85.DATA
//DDCLRP85 DD DISP=SHR,DSN=GENAPP.DDCLRP85.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZBI09140
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDBIIN86 DD DISP=SHR,DSN=GENAPP.DDBIIN86.DATA
//DDBIOT86 DD DISP=SHR,DSN=GENAPP.DDBIOT86.DATA
//DDBIRP86 DD DISP=SHR,DSN=GENAPP.DDBIRP86.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZRE09141
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN87 DD DISP=SHR,DSN=GENAPP.DDREIN87.DATA
//DDREOT87 DD DISP=SHR,DSN=GENAPP.DDREOT87.DATA
//DDRERP87 DD DISP=SHR,DSN=GENAPP.DDRERP87.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
