//VJOB0262 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZRE09481
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDREIN67 DD DISP=SHR,DSN=GENAPP.DDREIN67.DATA
//DDREOT67 DD DISP=SHR,DSN=GENAPP.DDREOT67.DATA
//DDRERP67 DD DISP=SHR,DSN=GENAPP.DDRERP67.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZAG09482
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDAGIN68 DD DISP=SHR,DSN=GENAPP.DDAGIN68.DATA
//DDAGOT68 DD DISP=SHR,DSN=GENAPP.DDAGOT68.DATA
//DDAGRP68 DD DISP=SHR,DSN=GENAPP.DDAGRP68.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZPA09483
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDPAIN69 DD DISP=SHR,DSN=GENAPP.DDPAIN69.DATA
//DDPAOT69 DD DISP=SHR,DSN=GENAPP.DDPAOT69.DATA
//DDPARP69 DD DISP=SHR,DSN=GENAPP.DDPARP69.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
