//VJOB0314 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZEN09637
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN43 DD DISP=SHR,DSN=GENAPP.DDENIN43.DATA
//DDENOT43 DD DISP=SHR,DSN=GENAPP.DDENOT43.DATA
//DDENRP43 DD DISP=SHR,DSN=GENAPP.DDENRP43.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZCU09638
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN44 DD DISP=SHR,DSN=GENAPP.DDCUIN44.DATA
//DDCUOT44 DD DISP=SHR,DSN=GENAPP.DDCUOT44.DATA
//DDCURP44 DD DISP=SHR,DSN=GENAPP.DDCURP44.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCL09639
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCLIN45 DD DISP=SHR,DSN=GENAPP.DDCLIN45.DATA
//DDCLOT45 DD DISP=SHR,DSN=GENAPP.DDCLOT45.DATA
//DDCLRP45 DD DISP=SHR,DSN=GENAPP.DDCLRP45.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
