//VJOB0427 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZHO09976
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN22 DD DISP=SHR,DSN=GENAPP.DDHOIN22.DATA
//DDHOOT22 DD DISP=SHR,DSN=GENAPP.DDHOOT22.DATA
//DDHORP22 DD DISP=SHR,DSN=GENAPP.DDHORP22.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZEN09977
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDENIN23 DD DISP=SHR,DSN=GENAPP.DDENIN23.DATA
//DDENOT23 DD DISP=SHR,DSN=GENAPP.DDENOT23.DATA
//DDENRP23 DD DISP=SHR,DSN=GENAPP.DDENRP23.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZCU09978
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDCUIN24 DD DISP=SHR,DSN=GENAPP.DDCUIN24.DATA
//DDCUOT24 DD DISP=SHR,DSN=GENAPP.DDCUOT24.DATA
//DDCURP24 DD DISP=SHR,DSN=GENAPP.DDCURP24.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
