//VJOB0303 JOB (ACCT),'VOLUME TEST',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,REGION=0M
//*
//* Generated volume-test JCL
//*
//STEP01   EXEC PGM=ZUW09604
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDUWIN10 DD DISP=SHR,DSN=GENAPP.DDUWIN10.DATA
//DDUWOT10 DD DISP=SHR,DSN=GENAPP.DDUWOT10.DATA
//DDUWRP10 DD DISP=SHR,DSN=GENAPP.DDUWRP10.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP02   EXEC PGM=ZMT09605
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDMTIN11 DD DISP=SHR,DSN=GENAPP.DDMTIN11.DATA
//DDMTOT11 DD DISP=SHR,DSN=GENAPP.DDMTOT11.DATA
//DDMTRP11 DD DISP=SHR,DSN=GENAPP.DDMTRP11.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//STEP03   EXEC PGM=ZHO09606
//STEPLIB  DD DISP=SHR,DSN=GENAPP.LOADLIB
//DDHOIN12 DD DISP=SHR,DSN=GENAPP.DDHOIN12.DATA
//DDHOOT12 DD DISP=SHR,DSN=GENAPP.DDHOOT12.DATA
//DDHORP12 DD DISP=SHR,DSN=GENAPP.DDHORP12.DATA
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//*
//
