-- Generated DDL for volume-test schema

CREATE DATABASE GENAAG;
CREATE DATABASE GENABI;
CREATE DATABASE GENACL;
CREATE DATABASE GENACU;
CREATE DATABASE GENAEN;
CREATE DATABASE GENAHO;
CREATE DATABASE GENAMT;
CREATE DATABASE GENAPA;
CREATE DATABASE GENARE;
CREATE DATABASE GENAUW;

CREATE TABLE GENAAG.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENAAG.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENAAG.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENAAG.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENAAG.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENAAG.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENAAG.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENAAG.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENAAG.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENAAG.COVER (CUSTOMERNUMBER);

CREATE TABLE GENAAG.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENAAG.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENAAG.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENAAG.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENAAG.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENAAG.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENAAG.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENAAG.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENAAG.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENAAG.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENAAG.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENAAG.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENAAG.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENAAG.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENAAG.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENAAG.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENAAG.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENAAG.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENAAG.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENAAG.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENAAG.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENAAG.RISK (CUSTOMERNUMBER);

CREATE TABLE GENAAG.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENAAG.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENAAG.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENAAG.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENAAG.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENAAG.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENABI.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENABI.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENABI.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENABI.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENABI.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENABI.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENABI.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENABI.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENABI.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENABI.COVER (CUSTOMERNUMBER);

CREATE TABLE GENABI.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENABI.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENABI.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENABI.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENABI.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENABI.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENABI.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENABI.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENABI.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENABI.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENABI.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENABI.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENABI.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENABI.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENABI.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENABI.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENABI.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENABI.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENABI.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENABI.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENABI.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENABI.RISK (CUSTOMERNUMBER);

CREATE TABLE GENABI.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENABI.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENABI.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENABI.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENABI.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENABI.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENACL.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENACL.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENACL.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENACL.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENACL.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENACL.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENACL.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENACL.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENACL.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENACL.COVER (CUSTOMERNUMBER);

CREATE TABLE GENACL.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENACL.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENACL.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENACL.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENACL.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENACL.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENACL.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENACL.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENACL.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENACL.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENACL.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENACL.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENACL.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENACL.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENACL.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENACL.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENACL.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENACL.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENACL.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENACL.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENACL.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENACL.RISK (CUSTOMERNUMBER);

CREATE TABLE GENACL.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENACL.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENACL.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENACL.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENACL.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENACL.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENACU.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENACU.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENACU.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENACU.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENACU.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENACU.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENACU.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENACU.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENACU.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENACU.COVER (CUSTOMERNUMBER);

CREATE TABLE GENACU.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENACU.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENACU.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENACU.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENACU.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENACU.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENACU.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENACU.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENACU.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENACU.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENACU.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENACU.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENACU.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENACU.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENACU.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENACU.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENACU.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENACU.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENACU.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENACU.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENACU.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENACU.RISK (CUSTOMERNUMBER);

CREATE TABLE GENACU.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENACU.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENACU.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENACU.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENACU.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENACU.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENAEN.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENAEN.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENAEN.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENAEN.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENAEN.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENAEN.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENAEN.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENAEN.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENAEN.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENAEN.COVER (CUSTOMERNUMBER);

CREATE TABLE GENAEN.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENAEN.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENAEN.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENAEN.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENAEN.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENAEN.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENAEN.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENAEN.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENAEN.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENAEN.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENAEN.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENAEN.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENAEN.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENAEN.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENAEN.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENAEN.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENAEN.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENAEN.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENAEN.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENAEN.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENAEN.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENAEN.RISK (CUSTOMERNUMBER);

CREATE TABLE GENAEN.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENAEN.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENAEN.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENAEN.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENAEN.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENAEN.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENAHO.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENAHO.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENAHO.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENAHO.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENAHO.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENAHO.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENAHO.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENAHO.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENAHO.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENAHO.COVER (CUSTOMERNUMBER);

CREATE TABLE GENAHO.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENAHO.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENAHO.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENAHO.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENAHO.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENAHO.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENAHO.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENAHO.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENAHO.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENAHO.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENAHO.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENAHO.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENAHO.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENAHO.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENAHO.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENAHO.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENAHO.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENAHO.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENAHO.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENAHO.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENAHO.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENAHO.RISK (CUSTOMERNUMBER);

CREATE TABLE GENAHO.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENAHO.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENAHO.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENAHO.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENAHO.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENAHO.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENAMT.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENAMT.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENAMT.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENAMT.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENAMT.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENAMT.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENAMT.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENAMT.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENAMT.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENAMT.COVER (CUSTOMERNUMBER);

CREATE TABLE GENAMT.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENAMT.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENAMT.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENAMT.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENAMT.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENAMT.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENAMT.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENAMT.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENAMT.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENAMT.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENAMT.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENAMT.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENAMT.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENAMT.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENAMT.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENAMT.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENAMT.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENAMT.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENAMT.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENAMT.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENAMT.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENAMT.RISK (CUSTOMERNUMBER);

CREATE TABLE GENAMT.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENAMT.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENAMT.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENAMT.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENAMT.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENAMT.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENAPA.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENAPA.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENAPA.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENAPA.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENAPA.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENAPA.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENAPA.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENAPA.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENAPA.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENAPA.COVER (CUSTOMERNUMBER);

CREATE TABLE GENAPA.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENAPA.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENAPA.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENAPA.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENAPA.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENAPA.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENAPA.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENAPA.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENAPA.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENAPA.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENAPA.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENAPA.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENAPA.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENAPA.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENAPA.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENAPA.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENAPA.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENAPA.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENAPA.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENAPA.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENAPA.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENAPA.RISK (CUSTOMERNUMBER);

CREATE TABLE GENAPA.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENAPA.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENAPA.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENAPA.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENAPA.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENAPA.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENARE.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENARE.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENARE.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENARE.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENARE.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENARE.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENARE.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENARE.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENARE.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENARE.COVER (CUSTOMERNUMBER);

CREATE TABLE GENARE.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENARE.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENARE.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENARE.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENARE.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENARE.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENARE.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENARE.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENARE.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENARE.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENARE.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENARE.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENARE.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENARE.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENARE.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENARE.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENARE.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENARE.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENARE.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENARE.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENARE.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENARE.RISK (CUSTOMERNUMBER);

CREATE TABLE GENARE.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENARE.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENARE.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENARE.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENARE.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENARE.SURCHARGE (CUSTOMERNUMBER);

CREATE TABLE GENAUW.ADDRESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ADDRESSX1
  ON GENAUW.ADDRESS (CUSTOMERNUMBER);

CREATE TABLE GENAUW.CLAIM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CLAIMX1
  ON GENAUW.CLAIM (CUSTOMERNUMBER);

CREATE TABLE GENAUW.COMMISSION (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COMMISSIX1
  ON GENAUW.COMMISSION (CUSTOMERNUMBER);

CREATE TABLE GENAUW.CONTACT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX CONTACTX1
  ON GENAUW.CONTACT (CUSTOMERNUMBER);

CREATE TABLE GENAUW.COVER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX COVERX1
  ON GENAUW.COVER (CUSTOMERNUMBER);

CREATE TABLE GENAUW.DISCOUNT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX DISCOUNTX1
  ON GENAUW.DISCOUNT (CUSTOMERNUMBER);

CREATE TABLE GENAUW.ENDORSE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX ENDORSEX1
  ON GENAUW.ENDORSE (CUSTOMERNUMBER);

CREATE TABLE GENAUW.EXCESS (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX EXCESSX1
  ON GENAUW.EXCESS (CUSTOMERNUMBER);

CREATE TABLE GENAUW.HISTORY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX HISTORYX1
  ON GENAUW.HISTORY (CUSTOMERNUMBER);

CREATE TABLE GENAUW.LEDGER (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX LEDGERX1
  ON GENAUW.LEDGER (CUSTOMERNUMBER);

CREATE TABLE GENAUW.PAYMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PAYMENTX1
  ON GENAUW.PAYMENT (CUSTOMERNUMBER);

CREATE TABLE GENAUW.POLICY (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX POLICYX1
  ON GENAUW.POLICY (CUSTOMERNUMBER);

CREATE TABLE GENAUW.PREMIUM (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX PREMIUMX1
  ON GENAUW.PREMIUM (CUSTOMERNUMBER);

CREATE TABLE GENAUW.RENEWAL (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RENEWALX1
  ON GENAUW.RENEWAL (CUSTOMERNUMBER);

CREATE TABLE GENAUW.RESERVE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RESERVEX1
  ON GENAUW.RESERVE (CUSTOMERNUMBER);

CREATE TABLE GENAUW.RISK (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX RISKX1
  ON GENAUW.RISK (CUSTOMERNUMBER);

CREATE TABLE GENAUW.SCHEDULE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SCHEDULEX1
  ON GENAUW.SCHEDULE (CUSTOMERNUMBER);

CREATE TABLE GENAUW.SETTLEMENT (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SETTLEMEX1
  ON GENAUW.SETTLEMENT (CUSTOMERNUMBER);

CREATE TABLE GENAUW.SURCHARGE (
  CUSTOMERNUMBER  INTEGER      NOT NULL,
  POLICYNUMBER    INTEGER      NOT NULL,
  ISSUEDATE       DATE         NOT NULL,
  EXPIRYDATE      DATE         NOT NULL,
  BROKERID        INTEGER               ,
  PAYMENT         DECIMAL(9,2)          ,
  LASTCHANGED     TIMESTAMP    NOT NULL,
  PRIMARY KEY (POLICYNUMBER)
);
CREATE INDEX SURCHARGX1
  ON GENAUW.SURCHARGE (CUSTOMERNUMBER);

